version: '3.5'
networks:
  backend-network:
    driver: bridge

services:
  back:
    build:
      context: ./
      dockerfile: ./back/Dockerfile
    environment:
      APP_PORT: 5000
    restart: always
    volumes:
    - ./back:/code
    ports:
    - 5000:5000
    networks:
     - backend-network